### PR TITLE
Refactoring + fixed NOSIGPIPE (with tests)

### LINKED ISSUE #37: Don't trap on SIGPIPE
We need to handle SIGPIPE without trapping, this is how Curassow solves it so a similar fix might be useful here: https://github.com/kylef/Curassow/pull/9

/cc @tannernelson

### PR DESCRIPTION
**Pull request by czechboy0**
- renamed TCPSocket to TCPInternetSocket (TCPSocket is now a protocol that encompasses even non-internet TCP sockets) - same for UDP
- added pipe() to allow for local testing by creating two connected sockets - useful for testing
- disabled SIGPIPE on all created sockets, tested in tests (that's where pipe() becomes useful)
- added a few very basic pipe tests, more will come in later PRs, this allows us to test the lower-level logic much more easily

Fixes #37, replaces #43.

/cc @tannernelson

### CODE REVIEW

File: Sources/SocksCore/TCPSocket.swift [hunk 1]
```diff
@@ -76,45 +58,84 @@ public class TCPSocket: InternetSocket {
...
+        self.address = address
+        self.closed = false
+        
+        self.reuseAddress = true
+    }
+    
+    public convenience init(address: InternetAddress) throws {
+        var conf: SocketConfig = .TCP(addressFamily: address.addressFamily)
+        let resolved = try address.resolve(with: conf)
+        try conf.adjust(for: resolved)
```
Comment (MatthiasKreileder) [inline Sources/SocksCore/TCPSocket.swift]: Could we move the logic of the adjust function to the InternetAddress extension function called "func resolve(with config: SocketConfig)"?
i.e. resolve() will adjust the config? I just want to minimize the risk that someone could forget to call adjust after resolving the address.

Comment (czechboy0) [inline Sources/SocksCore/TCPSocket.swift]: Very good point, I did something slightly different, but it makes it impossible to forget to adjust it now: https://github.com/czechboy0/Socks/pull/52

Thanks for noticing this
